# bind: Change main control
unbind C-b
set -g prefix C-space
bind C-space send-prefix

# bind: change split window
bind | split-window -h

bind v split-window -v
bind - split-window -v

# bind: keybind for fullscreen
bind f resize-pane -Z

# 1 based window
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

# Visual changes
set -sg terminal-overrides ",*:RGB"
set-option -ga terminal-overrides ",alacritty:Tc"
set -g default-terminal "alacritty"
set -g pane-border-lines simple 

# Theme: Status bar
set -g status-style "bg=#1f2335,fg=black,bright"
set -g status-left ""
set -g status-right "#[fg=white,bright]#S"

# Theme: Windows
set -g window-status-format " #W "
set -g window-status-current-format " #W "

set -g window-status-bell-style "bg=red,nobold"
set -g window-status-current-style "#{?window_zoomed_flag,bg=yellow,bg=blue\#,nobold}"
set -g window-status-style "bg=default,fg=white"

set -g status-right "#[fg=green]#S #[fg=white]| #[fg=yellow]%H:%M #[fg=white]| #[fg=cyan]%d-%b-%y"

# Theme: borders
set -g pane-active-border-style "fg=blue"

# Qol
set -g escape-time 0
set -g mouse on
set -g repeat-time 1000
set -g history-limit 10000
